version: '3.1'

services:
  postgresql:
    container_name: 'postgres_bd'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "seuemail@email.com"
      PGADMIN_DEFAULT_PASSWORD: "senha1"
    ports:
      - "3000:80"
    depends_on:
      - postgresql
    networks:
      - my_network

  python_app:
    build: ./app
    environment:
      - CLIENT_ID=2ee0ca64c6294613b3a0108fcea4505d
      - CLIENT_SECRET=44484c2643574b63937a85c18f34d59e
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgresql
      - DB_PORT=5432
    depends_on:
      - postgresql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
